// <auto-generated />
namespace AspMvcTest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _123zxc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123zxc));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301615379_123zxc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
